### ISSUE TITLE
AZ-100T04A-ENU-LabGuide error

### ISSUE THREAD

**Issue by tbkobberoe** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#1]
Exercise 1 Task 2: The Vnetname should be az1000402-vnet2, not az1000401-vnet2 in pt. 1, 2 and 3.

By the way, thx a lot for these labs, they saved/saves the last 2 days of my course

**Comment by TJGitHubUser** [comment]
These have been fixed. Thanks.
