### ISSUE TITLE
T01 interface changes

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#10]
wrong label in "AZ-100T01A", exercice 2, Task 2, Point 4 and 5
There is no more "New" blade but a "Create a Resource" option on the Hub menu.

**Comment by renaudwangler** [comment]
Same problem in the AZ-100T02A instructions file

**Comment by renaudwangler** [comment]
Same problem in the AZ-100T03A instructions file

**Comment by staleycyn** [comment]
New lab guides with corrected errors and typos will be posted on 28 January.
