### ISSUE TITLE
AZ-100T02A Labguide errors

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#11]
The AZ-100T02A labguide includes many errors and/or approximations that will make it complex to understand for our students.

For instance, the "navigate to the XXX blade" is repeatedly used instead of the way to open the blade ==> at point 8 of the task 1 of the first exercise (0), students need to click on "create" on the previously opened "Template deployment" blade to open the "Custom Deployment" blade...

**Comment by renaudwangler** [comment]
Another example : At point 10 of the task 1 from exercise 1, why is the json file labelled as found on an "F:" drive ?

**Comment by renaudwangler** [comment]
On point 10 of task 2 from exercice 1, if students follow the guide they should have the option of **enabling** the secure transfer requirement.

**Comment by renaudwangler** [comment]
on point 5 of task 4 from exercice 1, the copied container should read **az1000302-container** on the second storage account blob page

**Comment by renaudwangler** [comment]
On task 1 of exercise 2, the "properties" word should be avoided since a "properties" page is present in the current view and is not the object referred to in these tasks.

**Comment by renaudwangler** [comment]
On point 6 of task 2 from exercise 2, it should be wise to verify the name of the storage account share since the powershell connect output may skip characters in the azure portal (file share/connect blade)

**Comment by staleycyn** [comment]
These are good suggestions and as the instructor teaching the course, please feel free to implement your suggestions in the classroom. New lab guides with corrected errors and typos will be posted on 28 January. Also, our new lab guides are not designed to provided a step by step detailed lab solution. There should be sufficient information for students to follow the lab. Please feel free to comment on the MCT Forum.

**Comment by renaudwangler** [comment]
Sorry, was the purpose of the git not to alloy anyone help improving the classroom material quality ?
I really liked the fact that previous versions of courses was continuously updated by trainers.
You may change the main readme file of this git if you close these issues without them being solved in the current courseware release...
Writing these down took time and, of course, as an instructor "I feel free to implement (my) suggestions in the classroom"... I only hoped to be useful to some other instructors... sorry ...

**Comment by tiagocostapt** [comment]
@renaudwangler I had opened Issue #5 with the same exact topic. I love GitHub and this is so good for this kind of feedback by the trainers that are in the field teaching this. It is impossible for the team to check every step, every lab, every day! Trainers that are in the field do it and could provide great feedback. We were creating a great Azure MCT community in GitHub.

**Comment by renaudwangler** [comment]
yep @tiagocostapt , I did read your comment when it was opened and already regretted it was so quickly closed without discussion. I totally agree : we WERE creating great content in GitHub with the previous courses' format...

**Comment by amjadnkhan** [comment]
can someone add the pot files..that was great help to deliver the training
thanks
