### ISSUE TITLE
AZ-100T03A Labguide enhancement

### ISSUE THREAD

**Issue by renaudwangler** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#12]
On point 4 of the task 2 from exercise 1, the $subnetId would be more easyly found via this powershell command, since we just get the virtual network :  **$subnetId=$vnet.Subnets[0].Id**

**Comment by renaudwangler** [comment]
In addtion, some issues found in the previous lab(s) are present in this one too

**Comment by renaudwangler** [comment]
On Point 2 of task 1 from exercise 2, it would be nice to add **by clicking on the public IP value** to explain how to navigate from the vm blade to the public IP blade...

**Comment by staleycyn** [comment]
These are good suggestions and as the instructor teaching the course, please feel free to implement your suggestions in the classroom. New lab guides with corrected errors and typos will be posted on 28 January. Please use the MCT Forum for suggestions and teaching comments.
