### ISSUE TITLE
Any changelog?

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#13]
Ok, new guides are upload, replacing the old guides. So whats changed? As an MCT we have now idea what to expect and what to prepare before a class without any notice.
In the previous 2053x repositories we could simply see what labs changed much, what was added, removed, updated, fixed and which ones didn’t change at all.

I still prefer the previous ways of submitting lab guides. Why not do both and provide PDS and lab files in the release section of the github repository. Github has a build in mechanism  for version history. That doesn’t work if you upload pdfs in zipped format.
Azure is changing so often, MCTs don’t have time to figure out the changes in the labs themselves. 

Or maintain and upload a change log. 

Regards
Marcel

**Comment by polichtm** [comment]
Hi Marcel, 
appreciate the input - we are transitioning to the traditional approach - we'll be maintaining instructions/lab files on GitHub.
rgds
Marcin

**Comment by tiagocostapt** [comment]
@polichtm amazing work! Just checked the MD files!!! Now we can finally check what is different. :)

**Comment by polichtm** [comment]
Appreciated...
rgds
Marcin

**Comment by amjadnkhan** [comment]
ppt files can be added to make our life easy

**Comment by molenaar** [comment]
Thanks!

Marcel
