### ISSUE TITLE
Suggested edits for clairification and student confidence are shown in bold read in the attached document. 

### ISSUE THREAD

**Issue by DDHudson** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#14]
[az100-T01.docx](https://github.com/MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment/files/2799563/az100-T01.docx)

**Comment by polichtm** [comment]
Hi Dolores, 
appreciate your suggestions. We included more general ones applicable to multiple labs of this course in the README.md. Pls review them when you have a chance and let us know if you agree with their current format/content. We will add more specific ones to instructions of individual labs, wherever applicable.
Rgds
Marcin

**Comment by polichtm** [comment]
closing due to lack of response
