### ISSUE TITLE
AZ-100 Module 3 Lab - Error

### ISSUE THREAD

**Issue by MohamedHoosen** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#15]
Greetings 

I am attempting Module 3 Lab. I got an error when i typed code: Ex 1, Task 2 , No 6.

$nic = New-AzureRmNetworkInterface -Name "$($vmName)$(Get-Random)" -ResourceGroupName $resourceGroup.ResourceGroupName -Location $location -SubnetId $subnet
id -PublicIpAddressId $pip.ID -NetworkSecurityGroupId $nsg.ID

================================================================
Error is:
New-AzureRmNetworkInterface : Resource /subscriptions/d8b4e253-7747-48c7-99b7-a63c2562d973/resourceGroups/az1000301-RG/providers/Microsoft.Network/networkInterfaces/az1000301-vm12058684711/ipConfigurations/ipconfig1 is referencing public IP address /subscriptions/d8b4e253-7747-48c7-99b7-a63c2562d973/resourceGroups/az1000301-RG/providers/Microsoft.Network/publicIPAddresses/az1000301-vm1-ip that is already allocated to resource /subscriptions/d8b4e253-7747-48c7-99b7-a63c2562d973/resourceGroups/az1000301-RG/providers/Microsoft.Network/networkInterfaces/az1000301-vm12137489273/ipConfigurations/ipconfig1.
StatusCode: 400
ReasonPhrase: Bad Request
OperationID : '48f75f30-f511-4e39-9e36-8fffcb282ba4'
At line:1 char:8
+ $nic = New-AzureRmNetworkInterface -Name "$($vmName)$(Get-Random)" -R ...
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzNetworkInterface], NetworkCloudException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.Network.NewAzureNetworkInterfaceCommand
=================================================================
![image](https://user-images.githubusercontent.com/28430491/52346138-9d243e00-2a27-11e9-8148-bcd6fbd002eb.png)

Please help as to why this error would be, i have tried this a few times same error, ? Thanks

**Comment by renaudwangler** [comment]
Hi
I guess you get this error BECAUSE you did the operation multiple times ;)
The error messages states the "public IP" resource is allready linked to a nic.
I got a student that missspelled the previous command and a wrong named nic was created attached to the pip. We just deleted the first created nic and everything went fine.

Cheers !

**Comment by polichtm** [comment]
I'd fully agree with Renaud's assessment - pls give a try the suggestion above and let us know about the outcome
rgds
Marcin

**Comment by MohamedHoosen** [comment]
Morning All, 

thanks for your help.

This morning i didnt delete any nic, i ran the commands again, i got not errors. all worked. thanks

**Comment by polichtm** [comment]
Excellent - good to see...
rgds
Marcin
