### ISSUE TITLE
Which is the correct labguide?

### ISSUE THREAD

**Issue by MohamedHoosen** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#16]
Greetings 

**Please can you indicate which is the correct Lab Guide and Lab files to use.**

It is the one outside?
![image](https://user-images.githubusercontent.com/28430491/52346647-b4aff680-2a28-11e9-8c13-21f0ab6e6b2c.png)

or 

the must we use the one inside the 2 folders?
![image](https://user-images.githubusercontent.com/28430491/52346737-f9d42880-2a28-11e9-8475-b93dec53c1a8.png)
(Module 3 in here has repeated steps --> please check)

Please reply 

Thanks for the help

**Comment by polichtm** [comment]
Hi Muhamed,
the zip files contain lab guides in the PDF format - these are bound to become out of date with time. 
For up-to-date instructions, refer to markdown files in the Instructions folder
For lab files, refer to the Allfiles folder
Let us know if you have any additional questions
rgds
Marcin

**Comment by MohamedHoosen** [comment]
Hi Marcin

Ok thanks for explaining. 

I have found in the Instructions folder --> Mod 3 --> Exercise 1 --> Task 2 --> No 3. & 4 are the same.
also --> Mod 3 --> Exercise 1 --> Task 3 --> No.10 -->Virtual Network Name: az1000201-vnet1 --> shoudlnt this be az1000301-vnet1?

**Comment by polichtm** [comment]
Hi Mohamed, 
You are correct in both cases - I updated the instructions accordingly
rgds
Marcin
