### ISSUE TITLE
AZ-100T04A-ENU

### ISSUE THREAD

**Issue by martinezpat** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#17]
Exercise 0, task 1, step 10 loads the json template az-100-04_01_azuredeploy.json
In line 118, "computerName": "[variables('vm1Name')]",  needs to be 'vm2Name'.

If this is not corrected, the two VMs will have the same name (az1000401-vm1) and it will be confusing to the student when trying to complete Exercise 2, task 3, steps 5, 6, and 7.

**Comment by polichtm** [comment]
Hi Pat,
valid point - the template has been updated
rgds
Marcin
