### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by hfu949** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#19]
Looks like this line should be $storageAccount**2**Name instead of $storageAccount**1**Name.

In az-100-02__instructions.md,

$storageAccount2Key1 = (Get-AzureRmStorageAccountKey -ResourceGroupName 'az1000203-RG' -StorageAccountName $storageAccount1Name)[0].Value

**Comment by polichtm** [comment]
Valid point - updated
rgds
Marcin
