### ISSUE TITLE
Cleanup subscription

### ISSUE THREAD

**Issue by molenaar** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#26]
Please add a "cleanup resources" exercise/task at the end of all labs like the 20535 with az.

**Comment by tiagocostapt** [comment]
+1 for this request. I don't get tired to say to my students: delete the resource groups.. but when helping then I still see a lot of RGs.... When we had those in previous courses, students deleted then all the time. A small improvement that can help saving a lot of Azure credit.
