### ISSUE TITLE
extra Powerpoint zip included

### ISSUE THREAD

**Issue by trayhumphrey** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#3]
This is minor, but there is an extra zip included in the repo, AZ-100T05A-ENU-PowerPoint.zip. If I download the whole repo, the size of this extra file increases the total size considerably.

LOVE the new format and content! THANK YOU!

**Comment by trayhumphrey** [comment]
In this repo, there are lots of zips with lab instructions and lab files. There is one zip with PowerPoint decks that, I assume, wasn't intended for this repo. What I do when I teach is have each student download the whole repo as a zip from the Clone or Download button, then extract those on their local machine. The whole repo zipped is not large at 7.25MB, but the unnecessary PowerPoint file in the repo is 6.5MB of that.

 I attached two pics, one with the files of the repo, the other with the sizes of the files in the combined repo zip.

**Comment by trayhumphrey** [comment]
Well, I tried to attach 2 pics. Not sure if they made it. If my post in unclear, just click on the Code link for this repo and view the files in it. The PowerPoint zip, in my opinion, does not belong in this repo because it is neither lab instructions nor lab support files. It is for presentation and can be found, as you note, at MCTDLC. Thanks...

**Comment by staleycyn** [comment]
Got it. We will remove the PPT file from this repo. Thanks.

**Comment by amjadnkhan** [comment]
please keep all ppt thay was great help in understanding core concepts

**Comment by TJGitHubUser** [comment]
Yes this was included by mistake. PPT has been removed as it's available on the MCT download center. Thanks for flagging.
