### ISSUE TITLE
Change the Student login from student to Student

### ISSUE THREAD

**Issue by maximevoye** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#30]
User name: student needs to be Student (uppercase)
Lab 3 - exercice 2 - task 7

**Comment by polichtm** [comment]
Would you mind clarifying which module you are referring to?
rgds
Marcin

**Comment by maximevoye** [comment]
Hello,

inside : az-100-03__instructions.md // Exercice 2 / Task3.7

Student user name need an uppercase.
Because my students copy/past the user name and have an issue; The user name is Student, not student inside the VM. 
----
Use putty.exe to verify that you can successfully connect to az1000302-vm0 on its private IP address via the SSH protocol (TCP 22).

When prompted, authenticate by specifying the following values:

###     User name: student

    Password: Pa55w.rd1234

**Comment by polichtm** [comment]
completed
