### ISSUE TITLE
vm names incorrect

### ISSUE THREAD

**Issue by naarean** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#37]
According notes vm names are:

- Vm1Name: az1000401-vm0
- Vm2Name: az1000401-vm1

But in the JSON template it create them as vm1 & vm2.

Later in the exercise, it needs vm1 & vm2. so the initial name on the exercise readme are incorrect.

**Comment by polichtm** [comment]
Which JSON template are you referring to?
rgds
Marcin

**Comment by polichtm** [comment]
Here is how the values of vm1Name and vm2Name are assigned in the JSON template 
https://github.com/MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment/edit/master/Allfiles/Labfiles/AZ-100.4/az-100-04_01_azuredeploy.json:

        "vm1Name": {
            "type": "string",
            "defaultValue": "az1000401-vm1",
            "metadata": {
                "description": "VM1 name"
            }
        },
        "vm2Name": {
            "type": "string",
            "defaultValue": "az1000401-vm2",
            "metadata": {
                "description": "VM2 name"
            }
        },

Is this the template you are referring to? If so, the VMs you are deploying should be named this way (unless you explicilty change their names during deployment)
rgds
Marcin
