### ISSUE TITLE
AZ-100 Module 4 Lab - VM name miss matched

### ISSUE THREAD

**Issue by akunzai** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#43]
Caused by #17 and Duplicated with #37

Exercise 0, task 1, step 11 review the computerName was miss matched with [az-100-04_01_azuredeploy.json](https://github.com/MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment/blob/master/Allfiles/Labfiles/AZ-100.4/az-100-04_01_azuredeploy.json)

```diff
- Vm1Name: az1000401-vm0
+ Vm1Name: az1000401-vm1

- Vm2Name: az1000401-vm1
+ Vm2Name: az1000401-vm2
```

**Comment by polichtm** [comment]
updated
rgds
Marcin
