### ISSUE TITLE
Azure Portal Issue: az-100-03_instructions.md, Exercise 3, Task 3, Steps 5 and 6

### ISSUE THREAD

**Issue by StephenTrap** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#46]
To find the public IP, go to Home > Resource Group > az1000303-RG > az1000303vmss0-ip. 
For some reason it is not showing up in the scale set Overview.

**Comment by ianrgillespie** [comment]
Had the same problem earlier today

**Comment by polichtm** [comment]
resolved
