### ISSUE TITLE
Labs format - No more Markdown

### ISSUE THREAD

**Issue by tiagocostapt** [MicrosoftLearning/AZ-100-MicrosoftAzureInfrastructureDeployment#5]
Hi, are all the labs be only available in a PDF inside a ZIP file? 
This doesn't allow the community to help fix error, Azure Portal UI changes, etc... 
Any plans to change this?

**Comment by TJGitHubUser** [comment]
At this time, we are only releasing PDFs. Please continue this discussion on the MCT courseware forum. Thanks for responding.
